"""Small deterministic orchestration rules, never model choices."""

import re
from types import MappingProxyType

from app.agent.enums import AgentIntent
from app.agent.state import AgentState
from app.domain.enums import IssueCategory, Severity

SERVICE_DURATION_MINUTES_BY_CATEGORY = MappingProxyType(
    {
        IssueCategory.WATER_LEAK: 60,
        IssueCategory.ELECTRICAL: 60,
        IssueCategory.DOOR_LOCK: 60,
    }
)

# The resident UI should offer a short, actionable choice instead of exposing
# every slot generated by the lower-level scheduling query.
RESIDENT_SLOT_RESULT_LIMIT = 6

_EXPLICIT_CLOCK = re.compile(
    r"(?:上午|中午|下午|晚上)?\s*"
    r"(?:\d{1,2}|[零〇一二两三四五六七八九十]{1,3})"
    r"\s*(?:点|时|[:：]\s*\d{2})"
)


def requested_clock_has_passed(state: AgentState) -> bool:
    """Return whether this turn names a clock whose requested start has passed."""

    return bool(
        state.current_user_message
        and _EXPLICIT_CLOCK.search(state.current_user_message)
        and state.current_reference_time is not None
        and state.user_availability_windows
        and state.user_availability_windows[0].starts_at <= state.current_reference_time
    )


def apply_new_repair_defaults(state: AgentState) -> AgentState:
    """Set only approved non-safety defaults for a complete new repair."""

    updates: dict[str, object] = {}
    if state.issue_category is not None:
        updates["service_duration_minutes"] = SERVICE_DURATION_MINUTES_BY_CATEGORY[
            state.issue_category
        ]
    if (
        state.task_intent is not AgentIntent.NEW_REPAIR
        or state.safety_review_required
        or state.issue_category is None
        or state.missing_fields
    ):
        return state.model_copy(update=updates)
    severity = (
        state.cached_ticket_snapshot.severity if state.cached_ticket_snapshot else state.severity
    )
    updates["severity"] = severity or Severity.MEDIUM
    return state.model_copy(update=updates)
