"""Closed replay vocabularies persisted by migration 0006."""

from enum import StrEnum


class ReplayBundleStatus(StrEnum):
    CAPTURING = "CAPTURING"
    READY = "READY"
    INCOMPLETE = "INCOMPLETE"
    INVALID = "INVALID"
    UNAVAILABLE = "UNAVAILABLE"


class ReplayExecutionStatus(StrEnum):
    RUNNING = "RUNNING"
    PASSED = "PASSED"
    DIVERGED = "DIVERGED"
    INCOMPLETE = "INCOMPLETE"
    UNSUPPORTED_SCHEMA = "UNSUPPORTED_SCHEMA"
    FAILED_SAFE = "FAILED_SAFE"


class ReplayStepKind(StrEnum):
    NODE_ENTERED = "NODE_ENTERED"
    INTERPRETATION_RESULT = "INTERPRETATION_RESULT"
    PROPERTY_AUTHORIZATION_RESULT = "PROPERTY_AUTHORIZATION_RESULT"
    POLICY_RESULT = "POLICY_RESULT"
    DUPLICATE_LOOKUP_RESULT = "DUPLICATE_LOOKUP_RESULT"
    TICKET_SNAPSHOT_RESULT = "TICKET_SNAPSHOT_RESULT"
    SLOT_LOOKUP_RESULT = "SLOT_LOOKUP_RESULT"
    MCP_MUTATION_RESULT = "MCP_MUTATION_RESULT"
    OPERATOR_MUTATION_RESULT = "OPERATOR_MUTATION_RESULT"
    ROUTE_DECISION = "ROUTE_DECISION"
    INTERRUPT_RESULT = "INTERRUPT_RESULT"
    FINAL_STATE = "FINAL_STATE"


class ReplayMismatchType(StrEnum):
    NODE_SEQUENCE_MISMATCH = "NODE_SEQUENCE_MISMATCH"
    ROUTE_DECISION_MISMATCH = "ROUTE_DECISION_MISMATCH"
    EXTERNAL_CALL_ORDER_MISMATCH = "EXTERNAL_CALL_ORDER_MISMATCH"
    REQUEST_FINGERPRINT_MISMATCH = "REQUEST_FINGERPRINT_MISMATCH"
    INTERRUPT_MISMATCH = "INTERRUPT_MISMATCH"
    MUTATION_PLAN_MISMATCH = "MUTATION_PLAN_MISMATCH"
    FINAL_STATE_MISMATCH = "FINAL_STATE_MISMATCH"
    UNEXPECTED_REPLAY_CALL = "UNEXPECTED_REPLAY_CALL"
    UNCONSUMED_REPLAY_STEP = "UNCONSUMED_REPLAY_STEP"
    REPLAY_TAPE_MISS = "REPLAY_TAPE_MISS"
    SCHEMA_VERSION_MISMATCH = "SCHEMA_VERSION_MISMATCH"
    BUNDLE_CHECKSUM_MISMATCH = "BUNDLE_CHECKSUM_MISMATCH"


class RecoveryRecommendation(StrEnum):
    NO_ACTION_REQUIRED = "NO_ACTION_REQUIRED"
    OWNER_RESUME_REQUIRED = "OWNER_RESUME_REQUIRED"
    WAIT_FOR_RECONCILIATION = "WAIT_FOR_RECONCILIATION"
    OPERATOR_RECHECK_ALLOWED = "OPERATOR_RECHECK_ALLOWED"
    MANUAL_REVIEW_REQUIRED = "MANUAL_REVIEW_REQUIRED"
    REPLAY_EVIDENCE_INCOMPLETE = "REPLAY_EVIDENCE_INCOMPLETE"
    REPLAY_DIVERGED_REVIEW_REQUIRED = "REPLAY_DIVERGED_REVIEW_REQUIRED"
