"""Finite policy vocabulary for the FixFlow demonstration corpus."""

from enum import StrEnum


class PolicyTopic(StrEnum):
    SAFETY_ESCALATION = "SAFETY_ESCALATION"
    RESPONSIBILITY_SCOPE = "RESPONSIBILITY_SCOPE"
    IDENTITY_REQUIREMENT = "IDENTITY_REQUIREMENT"
    APPOINTMENT = "APPOINTMENT"
    RESCHEDULING = "RESCHEDULING"
    COMPLETION_ACCEPTANCE = "COMPLETION_ACCEPTANCE"
    REWORK = "REWORK"
    CANCELLATION = "CANCELLATION"
    HUMAN_ESCALATION = "HUMAN_ESCALATION"


class EvidenceSufficiency(StrEnum):
    SUFFICIENT = "SUFFICIENT"
    INSUFFICIENT = "INSUFFICIENT"
    CONFLICTING = "CONFLICTING"
