"""Agent-only intent and planning enums; none are persisted business status."""

from enum import StrEnum


class AgentIntent(StrEnum):
    NEW_REPAIR = "NEW_REPAIR"
    PROVIDE_INFORMATION = "PROVIDE_INFORMATION"
    QUERY_TICKET_STATUS = "QUERY_TICKET_STATUS"
    SELECT_APPOINTMENT_SLOT = "SELECT_APPOINTMENT_SLOT"
    RESCHEDULE_APPOINTMENT = "RESCHEDULE_APPOINTMENT"
    CANCEL_APPOINTMENT = "CANCEL_APPOINTMENT"
    CANCEL_TICKET = "CANCEL_TICKET"
    ACCEPT_REPAIR = "ACCEPT_REPAIR"
    REJECT_REPAIR = "REJECT_REPAIR"
    REQUEST_HUMAN = "REQUEST_HUMAN"
    UNKNOWN = "UNKNOWN"


class PendingAction(StrEnum):
    NONE = "NONE"
    CREATE_TICKET = "CREATE_TICKET"
    BOOK_APPOINTMENT = "BOOK_APPOINTMENT"
    RESCHEDULE_APPOINTMENT = "RESCHEDULE_APPOINTMENT"
    CANCEL_APPOINTMENT = "CANCEL_APPOINTMENT"
    CANCEL_TICKET = "CANCEL_TICKET"
    RECORD_ACCEPTANCE = "RECORD_ACCEPTANCE"


class AgentReconciliationStatus(StrEnum):
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    RESOLVED_COMMITTED = "RESOLVED_COMMITTED"
    RESOLVED_NOT_COMMITTED = "RESOLVED_NOT_COMMITTED"
    MANUAL_REVIEW = "MANUAL_REVIEW"


class SafetyFlag(StrEnum):
    IMMEDIATE_DANGER = "IMMEDIATE_DANGER"
    ACTIVE_FLOODING = "ACTIVE_FLOODING"
    ELECTRICAL_HAZARD = "ELECTRICAL_HAZARD"
    LOCKOUT_RISK = "LOCKOUT_RISK"
    OTHER_REVIEW_REQUIRED = "OTHER_REVIEW_REQUIRED"


class AcceptanceDecision(StrEnum):
    ACCEPT = "ACCEPT"
    REJECT = "REJECT"
    UNCLEAR = "UNCLEAR"


class IssueField(StrEnum):
    PROPERTY = "PROPERTY"
    ISSUE_CATEGORY = "ISSUE_CATEGORY"
    ISSUE_LOCATION = "ISSUE_LOCATION"
    ISSUE_DESCRIPTION = "ISSUE_DESCRIPTION"
    SEVERITY = "SEVERITY"
    AVAILABILITY = "AVAILABILITY"


class LLMRole(StrEnum):
    SYSTEM = "SYSTEM"
    USER = "USER"
    ASSISTANT = "ASSISTANT"
